### ISSUE TITLE
Native select doesn't show errors

### ISSUE THREAD

**Issue by egze** [fluxonui/fluxon#5]
### Fluxon UI Version

1.0.8

### Phoenix LiveView Version

1.0.0

### Current Behavior

Native selects don't show error messages, but if I remove the `native` attribute, then it does.

### Expected Behavior

Should work the same way.

### Browser

Safari

### Verification

- [X] I have searched for existing issues and confirmed this is not a duplicate
- [X] I have tested this issue with the latest version of Fluxon UI
- [ ] I have included all the information needed to reproduce this issue

**Comment by andrielfn** [comment]
Good catch! The native select variant was not only missing the errors, but also the labels and help text. I've just released 1.0.9 fixing that.

**Comment by egze** [comment]
I think the errors are still not shown for the native select.

**Comment by andrielfn** [comment]
Do you have a use case where this is happening? I can't reproduce it anymore in the latest Fluxon version.

```
<.select
  name="country"
  label="Native w/ errors"
  options={["Brazil", "Canada", "United States"]}
  native
  errors={["This is a error message"]}
/>
```

Does the above show the error message?

**Comment by egze** [comment]
I’m away from the computer for 3 days. What I remember is - I’m using `field={@form[:category]}`. Not sure if it does anything different, than setting the error explicitly.

**Comment by egze** [comment]
@andrielfn Confirmed - not working as expected. When the select is native, this part `if Phoenix.Component.used_input?(field)` is not returning `true`, and the errors are not assigned.

And this is because, when native and the select is not touched - the value is never sent in params. At least it's this way in Safari.

The changeset however does have the error:

```
source: #Ecto.Changeset<
      action: nil,
      changes: %{},
      errors: [
        category: {"can't be blank", [validation: :required]}, <--- THIS IS THE FIELD
```

**Comment by andrielfn** [comment]
So if `used_input?/1` is not returning true, that might be something with the form/changeset setup, right? Is it setting up the changeset `action` (ex `Map.put(:action, :validate)`)?

**Comment by egze** [comment]
Yes, it is setting the action.

```
def validate(%Phoenix.HTML.Form{} = form, params) do
    form.source.data
    |> changeset(params)
    |> Map.put(:action, :validate)
  end
```

It's not setting the error, because the value for the select is not sent in the params. So it thinks that the field has not been used. Yes, it has not been used - but the display of the validation should not be based anymore if it has been used or not - if the action is set.

**Comment by egze** [comment]
Why it works with a non-native select. It sends and empty value, even if not used

```
%{"_persistent_id" => "0", "category" => ""}
```

The native one, does not

**Comment by andrielfn** [comment]
Oh, I think I got it now. The problem is that I am setting the empty option as `disabled`, which prevents the form from submitting the field when this option is selected. Thanks for providing the details.

**Comment by andrielfn** [comment]
v1.0.12 published with the fix. Let me know if that works now.

**Comment by egze** [comment]
Works like a charm. Thank you for fixing!
